version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '20.4'
      - node/install-packages
      - run:
          name: "run tests"
          command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
